version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - jsegal205
  ignore:
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.2
    - 6.2.0
    - 6.2.4
    - 6.3.0
  - dependency-name: faker
    versions:
    - 5.3.1
    - 5.5.0
