language: node_js
node_js:
  - 12.12.0
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
before_script:
  - bash scripts/db_setup.sh
