language: node_js
node_js:
  - 12.12.0
install:
  - sudo apt-get install -yq --no-install-suggests --no-install-recommends postgresql-common
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-12 postgresql-client-12
  - sudo service postgresql start 12
before_script:
  - bash scripts/db_setup.sh
